version: '3'
services:
  mysql:
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=trading_signals_service
    ports:
      - 3307:3306
    container_name: trading-signal
  migration:
    build:
      context: ./
      dockerfile: Dockerfile-flyway-migration
    command: migrate
    depends_on:
      - mysql
    environment:
      - FLYWAY_URL=jdbc:mysql://mysql:3306/trading_signals_service
      - FLYWAY_USER=root
      - FLYWAY_PASSWORD=password
      - FLYWAY_BASELINE_ON_MIGRATE=true
      - FLYWAY_BASELINE_VERSION=0